// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYveuRl335jJPmlmSZyHWLdzWP6Mp3JE',
    appId: '1:736269045662:web:2012832ceb19a88117108f',
    messagingSenderId: '736269045662',
    projectId: 'companion-planner-and-notes',
    authDomain: 'companion-planner-and-notes.firebaseapp.com',
    storageBucket: 'companion-planner-and-notes.appspot.com',
    measurementId: 'G-CT2CT09L0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUqSwW9K0uHkhhEIVddmKsWb9hXSMo5KI',
    appId: '1:736269045662:android:5ec709be241d04a217108f',
    messagingSenderId: '736269045662',
    projectId: 'companion-planner-and-notes',
    storageBucket: 'companion-planner-and-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemwMXxes4rqS-lFHs1gUfuADNDmXN7xU',
    appId: '1:736269045662:ios:722c7642ff0681cf17108f',
    messagingSenderId: '736269045662',
    projectId: 'companion-planner-and-notes',
    storageBucket: 'companion-planner-and-notes.appspot.com',
    iosBundleId: 'com.example.companion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemwMXxes4rqS-lFHs1gUfuADNDmXN7xU',
    appId: '1:736269045662:ios:c2a1ac9ab42bd2f617108f',
    messagingSenderId: '736269045662',
    projectId: 'companion-planner-and-notes',
    storageBucket: 'companion-planner-and-notes.appspot.com',
    iosBundleId: 'com.example.companion.RunnerTests',
  );
}
